[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[target.'cfg(not(target_family = "wasm"))'.dependencies.bevy]
version = "0.13.2"
default-features = false
features = ["dynamic_linking"]

[target.aarch64-apple-darwin]
rustflags = [
  "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld", # Use LLD Linker
  "-Zshare-generics=y",                                      # (Nightly) Make the current crate share its generic instantiations
  "-Zthreads=0",                                             # (Nightly) Use improved multithreading with the recommended amount of threads.
]


